spring:
  liquibase:
    change-log: "classpath:liquibase/db/changelog/changelog.xml"
    contexts: main
  datasource:
    url: jdbc:postgresql://localhost:15432/taxi_fleet_db
    username: taxi_fleet
    password: taxi_fleet