services:
  taxi-fleet-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "15432:5432"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "username", "-d", "postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5
  taxi-fleet:
    build: ./
    container_name: taxi-fleet
    ports:
      - "8080:8080"
    depends_on:
      taxi-fleet-db:
        condition: service_healthy
    environment:
      - SERVER_PORT=8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/taxi_fleet_db

volumes:
  db-data: